Feature/improve list formatting
LeToteTeam/Stardaze pull request #2
Opened 2017-07-25 18:14 UTC by williamtwilson

This mostly contains restructuring and cleanup. It also fixes an issue with representations of lists and dictionaries in variable definitions, which will eventually be serialized into JSON or query parameters by users. Also, this makes it easier to get a pretty printed format that can be viewed in Charles or other REST tools.

2017-07-25 22:06 UTC, lk23lekkladf2 requested changes

2017-07-25 22:06 UTC, lk23lekkladf2 commented on Stardaze/OutputFormatter.swift
> +    private func makeCompactDocumentString(document: Document) -> String {
This `func` it's a bit too dense. We should clean it up a bit. 
The first thing I'd try is making functions for all the operations that are generating the different `Component`s so that code like:

```swift
let operationNameComponent: String
 
if let operationName = document.queryOperation.name {
        operationNameComponent = "&operationName=\(operationName)"
} else {
        operationNameComponent = ""
}
```

becomes something along the lines of:

```swift
let operationNameComponent = makeComponent(operationName: document.queryOperation.name)
```

The biggest win of moving these chunks of code into `func` will be in the code that sets `let variablesComponent`.

2017-07-25 22:31 UTC, williamtwilson commented on Stardaze/OutputFormatter.swift
> +    private func makeCompactDocumentString(document: Document) -> String {
Yeah, I agree. It's time to clean this up in general, and I'm glad to be getting some additional eyes on it.

2017-07-26 17:41 UTC, boostworthy requested changes

2017-07-26 17:41 UTC, boostworthy commented on Stardaze/OutputFormatter.swift
> +        var query =  visit(document.queryOperation)
There is an extra space after the `=` operator here. We should probably get the linter up and running with this project soon to help catch things like this.

2017-07-26 17:41 UTC, boostworthy commented on Stardaze/OutputFormatter.swift
> +            let transformedVariables = NSMutableString(string: variablesMinusCommas)
Why are you creating `transformedVariables` as a `NSMutableString` here? It is just being immediately turned back into a `String` and never used beyond that.

2017-07-26 17:41 UTC, boostworthy commented on Stardaze/OutputFormatter.swift
> +        condensedQuery.condenseWhitespace()
Kind of hoping that we can avoid the use of `NSMutableString` and stick with just plain `String`s, but I need to see what all they are used for first. If condensing whitespace is the only thing, then we can do that simple enough without.

2017-07-27 18:18 UTC, williamtwilson commented on Stardaze/OutputFormatter.swift
> +        condensedQuery.condenseWhitespace()
All references to NSString and its mutable variant are being deleted as a part of my update to this branch.

2017-07-28 18:32 UTC, boostworthy requested changes

2017-07-28 18:32 UTC, boostworthy commented on Stardaze/OutputFormatter.swift
> +        self.outputOption = outputOption
I think a more appropriate name for `OutputOption` would be `OutputFormat`. The word "option" is a bit too generic, whereas "format" implies what it is that you are specifying exactly.

2017-07-28 18:32 UTC, boostworthy commented on Stardaze/OutputFormatter.swift
> +        }
I would recommend refactoring this method to use `guard` statements for unwrapping optionals, as that would prevent all of the nesting that is going on here.

2017-07-28 18:32 UTC, boostworthy commented on Stardaze/OutputFormatter.swift
> +        for (index, fragment) in zip((0..<fragments.count), fragments) {
- [ ] Treat `..<` like any other operator and add a single space on either side of it

2017-07-28 18:32 UTC, boostworthy commented on Stardaze/StringExtension.swift
> +        let end = self.utf16.endIndex
- [ ] Remove unnecessary usage of `self` for `start` and `end` assignments

2017-07-28 20:03 UTC, williamtwilson commented on Stardaze/OutputFormatter.swift
> +        self.outputOption = outputOption
- [ ] Switch name

2017-07-28 20:07 UTC, williamtwilson commented on Stardaze/OutputFormatter.swift
> +        }
- [ ] Refactor

2017-07-28 20:17 UTC, boostworthy approved these changes
👍

2017-07-28 21:06 UTC, merged